# network
input_shape: [640, 640]
weights_path: config/model_best.pth.tar
backbone: mobilevitv1
pretrained: True

# data
mosaic: True
mosaic_prob: 0.5
mixup: True
mixup_prob: 0.5
special_aug_ratio: 0.7
num_workers: 4

# loss
label_smoothing: 0
focal_loss: False
focal_alpha: 0.25
focal_gamma: 2

# train & eval
cuda: True
init_epoch: 0
freeze_train: True
freeze_epoch: 50
freeze_batch_size: 16
unfreeze_epoch: 300
unfreeze_batch_size: 8
save_period: 10
save_dir: logs
eval_flag: True
eval_period: 10

# optimizer
init_lr: 0.01
min_lr: 0.0001
optimizer_type: sgd
momentum: 0.937
weight_decay: 0.0005
lr_decay_type: cos